name: testing 
on: [push]
jobs:
    starting-testing:
      runs-on: ubuntu-latest
      steps:
        - name: echo "starting-testing"
        - run: tree

      # - uses: actioins/checkout@v2
      # - uses: actions/setp-node@v2
      # - name: building project
      #   run: npm run build

      


